version: '3'
services:
  web:
    build: .
    image: pizzamachine
    env_file: .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 5000:5000

  db:
    image: postgres
    restart: always
<<<<<<< HEAD
    # volumes:
    #   - ./data:/var/lib/postgresql/data
=======
>>>>>>> sockt.io
    environment:
      - POSTGRES_DB=pizza
